website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logado com sucesso!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Senha incorreta.', category='error')
        else:
            flash('Email não existe.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        print("POST")
        email = request.form.get('email')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('\'Email\' já existe.', category='error')
            print("Existe")
        elif len(email) < 4:
            flash('\'Email\' precisa ser maior que 3 caracteres.', category='error')
            print("Maior")
        elif len(name) < 2:
            flash('\'Nome\' precisa ter mais de uma letra.', category='error')
            print("MENOS UM")
        elif password1 != password2:
            flash('\'Senhas\' são diferentes.', category='error')
            print("Diferentes")
        elif len(password1) < 7:
            flash('\'Senha\' precisa ter pelo menos 7 caracteres.', category='error')
            print("SETE")
        else:
            new_user = User(email=email, name=name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Conta criada!', category='success')
            print("Criado")
            return redirect(url_for('views.home'))
    print("GET")

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, Response, template_rendered
from flask_login import login_required, current_user
from .models import Note
from . import db
import json
import cv2

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)

@views.route('/cam_profile/<id>')
def cam_profile(id):
    return render_template("cam_profile.html", id=id, user=current_user)

def generateVideo():

    cap = cv2.VideoCapture("http://187.19.166.182/mjpg/video.mjpg")
    #cap = cv2.VideoCapture("./static/video.mp4") 
    #no_image_hero = cv2.imread("/")

    while True:
        ret, img = cap.read()
        if ret == True:
            img = cv2.resize(img, (0,0), fx=0.5, fy=0.5)
            frame = cv2.imencode('.jpg', img)[1].tobytes()
            yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
            time.sleep(0.1)
        else:
            yield "no-video"
        

@views.route("/video_feed")
def video_feed():
    return Response(generateVideo(), mimetype='multipart/x-mixed-replace; boundary=frame')

@views.route("/data_feed")
def data_feed():
    return {"fps":"0","counter":"1","mediumVelocity":"10","mediumDensity":"12","rpiName":"1231"}

website/templates/base.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='/css/base.css') }}"
      rel="stylesheet"
    />

    <title>{% block title%}webradar | Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-light" style="background-color: #f2f2f2">
      <div class="container-fluid">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <div class="d-flex justify-content-between">
            <a class="navbar-brand" href="/">
              <!--<img
                src="{{ url_for('static', filename='/images/ims_icon.png') }}"
                alt="webradar logo"
                class="d-inline-block align-text-top"
                style="width: 1.5em; max-width: 64px"
              />-->
              <img
                src="../static/images/ims_logo.png"
                alt="webradar logo"
                class="d-inline-block align-text-top"
                style="width: 2em; max-width: 128px"
              />
            </a>

            <!---->
            {% if user.is_active %}
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-expanded="false"
                  style="color: #f00a0a"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="user-icon"
                    viewBox="0 0 16 16"
                    fill="black"
                  >
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                    <path
                      d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z"
                    />
                  </svg>
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Planos</a></li>
                  <li>
                    <a class="dropdown-item" href="#">Ajustes</a>
                  </li>
                  <li><hr class="dropdown-divider" /></li>
                  <li><a class="dropdown-item" href="/logout">Sair</a></li>
                </ul>
              </li>
            </ul>
            {% endif %}
            <!---->
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.slim.js"
      integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <article>{% block content %}{% endblock %}</article>

    <footer class="p-4 d-flex justify-content-end">
      <p class="footer-text">
        &copy <b>IMS</b><span style="color: #f00a0a; font: bold"> | </span>2022
      </p>
    </footer>
  </body>
</html>

website/templates/cam_profile.html
{% extends "base.html" %} {% block content%}
<link rel="stylesheet" href="../static/css/cam-profile.css" />
<div class="container">
  <br />
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card">
        <img class="video-img" src="{{ url_for('views.video_feed')}}" />
        <div class="card-body">
          <h5 class="card-title">
            Trecho #001 | <b style="color: #53c398">Ao vivo</b>
          </h5>
          <br />
          <small>Mainframe-id: <span id="rpiName"></span></small>
          <hr />
          <p class="card-text">
            <small style="color: darkgray; font-weight: bold"
              >Localização: BR040 - KM 192 | Concessão: CONCER Ltda.</small
            >
          </p>
          <table class="table table-striped" style="font-size: smaller">
            <thead>
              <tr>
                <th scope="col">Info</th>
                <th scope="col">Atual</th>
                <th scope="col">Média</th>
                <th scope="col">Menor</th>
                <th scope="col">Maior</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">FPS</th>
                <td id="fps"></td>
                <td>--</td>
                <td>--</td>
                <td>--</td>
              </tr>
              <tr>
                <th scope="row">Contador #01</th>
                <td id="counter"></td>
                <td>--</td>
                <td>--</td>
                <td>--</td>
              </tr>

              <tr>
                <th scope="row">Velocidade</th>
                <td>--</td>
                <td id="mediumVelocity">--</td>
                <td>--</td>
                <td>--</td>
              </tr>

              <tr>
                <th scope="row">Densidade/faixa</th>
                <td>--</td>
                <td id="mediumDensity">--</td>
                <td>--</td>
                <td>--</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="card-body">
          <a href="#" class="card-link">Criar contador</a>
          <a href="#" class="card-link">Exportar dados(CSV)</a>
          <a href="#" class="card-link">Mais câmeras</a>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
  <br />
</div>

<script>
  function fetchdata() {
    $.ajax({
      url: "{{ url_for('views.data_feed')}}",
      type: "get",
      success: function (data) {
        //console.log("200 OK:" + JSON.stringify(data));

        $("#rpiName").text(data["rpiName"]);
        $("#fps").text(data["fps"]);
        $("#counter").text(data["counter"]);
        $("#mediumVelocity").text(data["mediumVelocity"]);
        $("#mediumDensity").text(data["mediumDensity"]);
      },
      complete: function (data) {
        setTimeout(fetchdata, 400);
      },
      dataType: "json",
    });
  }

  $(document).ready(function () {
    setInterval(fetchdata(), 500);
  });
</script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<link rel="stylesheet" href="../static/css/home.css" />
<div class="container">
  <br />
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="row">
        {% if true %}

        <div class="col">
          <div class="card cam-card">
            <img
              src="{{ url_for('views.video_feed')}}"
              class="card-img-top"
              alt="..."
            />
            <div class="card-body">
              <p class="card-text">
                Localização: BR040 - KM 192<br />Concessão: CONCER Ltda.<br /><b
                  style="color: #53c398"
                  >Online</b
                >
              </p>
            </div>
          </div>
        </div>
        {% else %}
        <div class="col">
          <div class="card">
            <div class="card-header">Adicionar estrada</div>
            <div class="card-body">
              <h5 class="card-title">Bem-vindo, {{user.name}} !</h5>
              <p class="card-text">Para começar, adicione uma estrada.</p>
              <a href="#" class="btn btn-primary">Adicionar</a>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $(".cam-card").on("click", function () {
      window.location = "/cam_profile/1";
    });
  });
</script>
{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>WEB RADAR | Início</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6"><label>TRECHO #0001</label></div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <img src="{{ url_for('video_feed')}}" />
        </div>
        <div class="col-md-4"></div>
        <div class="col-md-4"></div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<link rel="stylesheet" href="../static/css/login.css" />
<div class="root">
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <!--INICIO DA COLUNA DE LOGIN-->

            <div class="pt-3">
              <h1 class="text-center title-h1">Entrar</h1>
            </div>
            <div>
              <h6 class="text-center">
                One step to <span style="color: #f00a0a">know</span>
              </h6>
            </div>
            <div>
              <form method="post" class="p-4">
                <div class="form-floating d-flex justify-content-center mb-4">
                  <input
                    type="text"
                    class="form-control rounded-0"
                    id="input-user"
                    name="email"
                    placeholder="email"
                  />
                  <label for="email">Email</label>
                </div>
                <div class="form-floating mb-4">
                  <input
                    type="password"
                    class="form-control rounded-0"
                    id="input-senha"
                    name="password"
                    placeholder="password"
                  />
                  <label for="password">Senha</label>
                </div>
                <div class="d-flex justify-content-between mb-5">
                  <a
                    href="/sign-up"
                    class="btn btn-dark me-4"
                    style="width: 50%"
                    id="sign-in-button"
                  >
                    <span style="font-weight: bold">Sign up</span>
                  </a>
                  <button
                    type="submit"
                    class="btn btn-primary ms-4"
                    style="width: 50%"
                  >
                    <span style="font-weight: bold">Login</span>
                  </button>
                </div>
                <div class="text-center">
                  <a
                    href="#"
                    target="_blank"
                    rel="noopener noreferrer"
                    title="Esqueci minha senha"
                    class="text-decoration-none forgot-password-link"
                  >
                    Esqueci minha senha
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript"></script>
  {% endblock %}
</div>

website/templates/users.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{user_name}} profile</title>
  </head>
  <body>
    <h2><i>Welcome, {{user_name}}.</i></h2>
  </body>
</html>